FROM mongo:bionic

VOLUME ["/data/db"]
WORKDIR /data

# docker volume create mongo-data
# docker run --rm -d --network vdh-network --name vdh-db -v mongo-data:/data/db db-container

# use vdhObservationCollection
# db.vdhObservationCollection.insertOne({id: "test"})
# db.getCollection("vdhObservationCollection").find()
